---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gophy
    name: gophy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gophy
  type: LoadBalancer
status:
  loadBalancer: {}
